name: Use Github Secrets

on:
  push:
    branches:
      - master

jobs:
  use-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Echo Secrets
      run: |
        ls
        echo ${{ secrets.SECRET_VAR }}